import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { comparePages, readContent, projectRoot, fileExists, type PageNode } from './index.ts';
import { buildVariants } from '../photos/variants.ts';
import { findTags } from './components.ts';
import { buildFigures } from './figures.ts';
import { isEssay, type CatalogPage } from './schema.ts';
import type { Plugin } from 'vite';

async function writeChanged(file: string, text: string) {
	if (!(await fileExists(file)) || (await readFile(file, 'utf8')) !== text)
		await writeFile(file, text);
}

/** The header lists top-level pages unless a page opts out; deeper pages never appear. */
function inNavigation(page: PageNode) {
	return page.metadata.nav ?? (page.depth === 1 && page.metadata.listed);
}

export async function generateContent({ strict = true } = {}) {
	const { pages, photos, photoEssays } = await readContent(projectRoot, { strict });
	const images = await buildVariants(photos, projectRoot, photoEssays);
	const figures = await buildFigures(pages, projectRoot);
	const imageById = new Map(images.map((image) => [image.id, image]));
	const output = path.join(projectRoot, 'src/lib/content/.generated');
	await mkdir(output, { recursive: true });

	// A page that names its own photographs carries each one under that name.
	// A photograph the body places with <Photo> is not repeated in the closing sequence.
	const catalogPages: CatalogPage[] = pages.map((page) => {
		const { images: named, cover, ...metadata } = page.metadata;
		const placed = new Set(
			findTags(page.body, ['Photo'])
				.map((tag) => tag.attributes.of)
				.filter(Boolean)
		);
		const essay = isEssay(page.metadata);
		return {
			...metadata,
			modified: page.modified,
			figures: figures.get(page.route)!,
			route: page.route,
			parent: page.parent,
			name: page.name,
			depth: page.depth,
			directory: page.directory,
			children: page.children,
			images: essay
				? Object.entries(named!).map(([alias, id]) => ({
						...imageById.get(id)!,
						alias,
						placed: placed.has(alias)
					}))
				: [],
			cover: essay ? (cover ? (imageById.get(named![cover])?.src ?? null) : null) : (cover ?? null),
			// Either the page names photographs of its own, or it places the gallery.
			viewer: essay || findTags(page.body, ['PhotoGrid']).length > 0
		};
	});

	const catalog = {
		pages: catalogPages,
		navigation: pages
			.filter(inNavigation)
			.toSorted(comparePages)
			.map((page) => ({ path: page.route, label: page.metadata.title })),
		sitemap: pages.filter((page) => page.metadata.listed).map((page) => page.route),
		galleryImages: images.filter(
			(image) => photos.find((photo) => photo.id === image.id)?.gallery.included
		),
		images
	};

	const modules = pages.map(
		(page, index) =>
			`import Body${index} from ${JSON.stringify(path.relative(output, path.join(projectRoot, page.file)).split(path.sep).join('/'))};`
	);
	await writeChanged(path.join(output, 'catalog.json'), JSON.stringify(catalog, null, '\t') + '\n');
	await writeChanged(
		path.join(output, 'bodies.ts'),
		`// Generated by scripts/content/generate.ts. Edit src/content instead.\nimport type { Component } from 'svelte';\n${modules.join('\n')}\nexport const bodies: Record<string, Component> = {\n${pages.map((page, index) => `${JSON.stringify(page.route)}: Body${index}`).join(',\n')}\n};\n`
	);
	return catalog;
}

export function contentWatchPlugin(): Plugin {
	let pending = Promise.resolve();
	return {
		name: 'nebve-content',
		configureServer(server) {
			server.watcher.add([path.join(projectRoot, 'src/content'), path.join(projectRoot, 'static')]);
			const update = (filename: string) => {
				const authored = filename.startsWith(path.join(projectRoot, 'src/content/'));
				const staticImage =
					filename.startsWith(path.join(projectRoot, 'static/')) &&
					/\.(svg|png|jpe?g|webp)$/i.test(filename);
				const generatedImage = ['photography', 'figures'].some((name) =>
					filename.startsWith(path.join(projectRoot, `static/images/${name}/`))
				);
				if ((!authored && !staticImage) || generatedImage) return;
				pending = pending.then(async () => {
					try {
						await generateContent({ strict: false });
						server.ws.send({ type: 'full-reload' });
					} catch (error) {
						const message = error instanceof Error ? error.message : String(error);
						server.config.logger.error(message);
						server.ws.send({ type: 'error', err: { message, stack: '', plugin: 'nebve-content' } });
					}
				});
			};
			server.watcher.on('add', update).on('change', update).on('unlink', update);
			server.httpServer?.once('close', () => {
				server.watcher.off('add', update).off('change', update).off('unlink', update);
			});
		}
	};
}
